# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: windows-latest

jobs:
- job: Demo
  steps:
  - powershell: |
      $Id = $(git rev-parse HEAD)
      Write-Output "$Id"
      $hashId = $Id.Remove($Id.Length – 34)
      Write-Host "##vso[task.setvariable variable=commitId;]hashId"
    displayName: 'PowerShell Script'

  - powershell: |
      $LoginParameters = @{
      Uri             = 'https://app.launchdarkly.com/api/v2/accelerate/deployment-events'
      Method          = 'POST'
      Body            = @{
          "projectKey": "rp-eap-test-project",
          "environmentKey": "test",
          "applicationKey": "login-service",
          "version": "$(commitId)",
          "eventType": "Started"
              }
            }
      $LoginResponse = Invoke-WebRequest @LoginParameters -ContentType 'application/json' -Headers @{"Authorization" = "api-f4face29-5244-4ec0-9d2e-3386e4f76287" }
      $LoginResponse.statuscode
    displayName: 'Build Started Script'

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
