# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: windows-latest

variables:
- group: LaunchDarkly-VG

jobs:
- job: Demo
  steps:
  - powershell: |
      $Id = $(git rev-parse HEAD)
      Write-Output "$Id"
      $hashId = $Id.Remove($Id.Length – 34)
      Write-Host "##vso[task.setvariable variable=commitId]$hashId"
    displayName: 'PowerShell Script'

  - powershell: |
      Write-Host "$(commitId)"
    displayName: 'PowerShell Script'

  - powershell: |
      $headers = @{
        "Authorization" = "$(apiKeyLD)"
        "Content-Type" = "application/json"
      }
      $json = '{
          "projectKey": "$(projectKey)",
          "environmentKey": "$(environmentKey)",
          "applicationKey": "$(applicationKey)",
          "version": "$(commitId)",
          "eventType": "$(eventTypeStrt)"
      }'
      $headers
      $json
      $response = Invoke-WebRequest -Uri 'https://app.launchdarkly.com/api/v2/accelerate/deployment-events' -Method 'POST' -Body $json -Headers $headers
      write-output "Status Code : " $response.statuscode
    displayName: 'Build Started Script'

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
